language: node_js
node_js:
  - 12
  - 14
  - 16
script:
  - echo '********Starting build*********'
  - echo 'Installing dependencies'
  - npm install
  - echo 'Starting test'
  - node index.js
notifications:
  email:
    recipients:
      - justin@justinpooters.nl
    on_success: always
    on_failure: always
